version: "3.9"
services:
  management:
    build: ./management-ui
    deploy:
      replicas: 1
    labels:
     - traefik.http.routers.management.rule=PathPrefix(`/management`)
     - traefik.http.routers.management.middlewares=management-stripprefix
     - traefik.http.middlewares.management-stripprefix.stripprefix.prefixes=/management
     - traefik.http.services.management.loadbalancer.server.port=3000
     - traefik.http.services.management.loadbalancer.sticky.cookie.name=session
    ports:
     - "3000:3000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
  static:
    build: ./static
    deploy:
      replicas: 1
    labels:
     - traefik.http.routers.static.rule=PathPrefix(`/static`)
     - traefik.http.routers.static.middlewares=static-stripprefix
     - traefik.http.middlewares.static-stripprefix.stripprefix.prefixes=/static
     - traefik.http.services.static.loadbalancer.server.port=80
     - traefik.http.services.static.loadbalancer.sticky.cookie.name=session
  dynamic:
    build: ./dynamic
    deploy:
      replicas: 1
    labels:
     - traefik.http.routers.dynamic.rule=PathPrefix(`/dynamic`)
     - traefik.http.routers.dynamic.middlewares=dynamic-stripprefix
     - traefik.http.middlewares.dynamic-stripprefix.stripprefix.prefixes=/dynamic
     - traefik.http.services.dynamic.loadbalancer.server.port=3000
  reverse-proxy:
    image: traefik:v2.6
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
